{% set name = "fenics-basix" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://github.com/fenics/basix/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7cd5a8b053219941e84068731b88338002f1f09dfc73dcd41f9cd584588dc65a

build:
  skip: true  # [win or python_impl == 'pypy']
  number: 0

outputs:
  - name: fenics-libbasix
    script: build-libbasix.sh
    build:
      run_exports:
        - {{ pin_subpackage("fenics-libbasix", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - libblas
        - libcblas
        - liblapack
        - xtensor
    test:
      commands:
        - test -f $PREFIX/lib/libbasix${SHLIB_EXT}
  - name: fenics-basix
    script: build-basix-py.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
      host:
        - python
        - pip
        - pybind11
        - xtensor
        - {{ pin_subpackage('fenics-libbasix', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('fenics-libbasix', exact=True) }}
        - numpy
    test:
      requires:
        - pytest
        - pytest-xdist
      source_files:
        - test
      imports:
        - basix
      commands:
        - pytest -v test/test_create.py


about:
  home: https://fenicsproject.org
  summary: Basix is a finite element definition and tabulation runtime library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.fenicsproject.org/basix/main/
  dev_url: https://github.com/fenics/basix

extra:
  feedstock-name: fenics-basix
  recipe-maintainers:
    - minrk
