{% set name = "fenics-basix" %}
{% set version = "0.9.0" %}

{% if win and cxx_compiler_version is not defined %}
{# windows doesn't set cxx compiler version, get year out of 'vs2022' #}
{% set cxx_compiler_version = cxx_compiler | replace("vs", "") %}
{% endif %}
{% set abi_version = "0.{}.{}".format(nanobind, cxx_compiler_version) %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://github.com/fenics/basix/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 60e96b2393084729b261cb10370f0e44d12735ab3dbd1f15890dec23b9e85329

build:
  skip: true  # [python_impl == 'pypy' or py<39]
  number: 0
  force_use_keys:
    # separate builds for each Python
    # this duplicates libbasix outputs, but results in faster builds
    - python

outputs:
  - name: fenics-libbasix
    script: build-libbasix.sh  # [not win]
    script: build-libbasix.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("fenics-libbasix", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - make  # [unix]
        - pkg-config
      host:
        - libblas
        - libcblas  # not linked, but needed for FindLAPACK during build
        - liblapack
    test:
      commands:
        - test -f $PREFIX/lib/libbasix${SHLIB_EXT}  # [not win]
        - if exist %LIBRARY_PREFIX%\bin\basix.dll (exit 0) else (exit 1)  # [win]

  - name: fenics-basix
    script: build-basix-py.sh  # [not win]
    script: build-basix-py.bat  # [win]
    build:
      run_exports:
        - fenics-basix-nanobind-abi =={{ abi_version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - make
        - pkg-config
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - nanobind  # [build_platform != target_platform]
      host:
        - scikit-build-core
        - python
        - pip
        - nanobind
        # - nanobind-abi
        - {{ pin_subpackage('fenics-libbasix', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('fenics-libbasix', exact=True) }}
        - numpy >=1.21
        - fenics-basix-nanobind-abi =={{ abi_version }}
    test:
      requires:
        - pytest
        - pytest-xdist
        # make sure the abi constraint is on an installable package
        - {{ cxx_compiler }}  # [not win]
        - {{ cxx_compiler }}_impl_{{ target_platform }}  # [not win]
        - vs_{{ target_platform }}  # [win]
        - {{ compiler("cxx") }}
      source_files:
        - test
      imports:
        - basix
      commands:
        - pytest -v test/test_create.py

  - name: fenics-basix-nanobind-abi
    version: "{{ abi_version }}"
    build:
      force_use_keys:
        - python
      run_exports:
        strong:
          - fenics-basix-nanobind-abi =={{ abi_version }}

    requirements:
      run_constrained:
        # nanobind doesn't yet have an abi metapacakage,
        # but hope it doesn't get bumped in patch releases
        - nanobind {{ nanobind }}.*
        # we shouldn't need to restrict compiler version,
        # but nanobind includes compiler version in the ABI
        # pin both compiler by name and _impl_ package
        # clangxx_impl_osx-64 depends on clangxx,
        # while gxx depends on gxx_impl_linux-64
        - {{ cxx_compiler }} {{ cxx_compiler_version }}.*  # [not win]
        - {{ cxx_compiler }}_impl_{{ target_platform }} {{ cxx_compiler_version }}.*  # [not win]
        # Windows only has vs_win-64 2022.11
        # it's unclear if the .11 is required
        - vs_{{ target_platform }} {{ cxx_compiler_version }}.*   # [win]

    test:
      commands:
        - echo 'ok'
about:
  home: https://fenicsproject.org
  summary: Basix is a finite element definition and tabulation runtime library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.fenicsproject.org/basix/main/
  dev_url: https://github.com/fenics/basix

extra:
  feedstock-name: fenics-basix
  recipe-maintainers:
    - minrk
