schema_version: 1

context:
  name: fenics-basix
  version: 0.9.0
  # cxx_compiler_version not specified on Windows
  # extract from cxx_compiler
  cxx_compiler_version: ${{ cxx_compiler_version | default(cxx_compiler | replace("vs", "")) }}
  # abi_version: 1.${{ nanobind_abi }}.${{ cxx_compiler_version }}
  abi_version: 0.${{ nanobind }}.${{ cxx_compiler_version }}

recipe:
  name: ${{ name|lower }}-meta
  version: ${{ version }}

source:
  url: https://github.com/fenics/basix/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 60e96b2393084729b261cb10370f0e44d12735ab3dbd1f15890dec23b9e85329

build:
  number: 3
  variant:
    use_keys:
      - python

outputs:
  - package:
      name: fenics-libbasix
    build:
      script: build-libbasix
    requirements:
      build:
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
        - cmake
        - if: unix
          then: make
        - pkg-config
      host:
        - libblas
        - libcblas  # not linked, but needed for FindLAPACK during build
        - liblapack
      run_exports:
        - ${{ pin_subpackage("fenics-libbasix", upper_bound="x.x.x") }}
    tests:
      - package_contents:
          lib: basix
  - package:
      name: fenics-basix
    build:
      script: build-basix-py
    requirements:
      build:
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
        - cmake
        - make
        - pkg-config
        - if: build_platform != target_platform
          then: 
            - python
            - cross-python_${{ target_platform }}
            - nanobind
            # - nanobind-abi
      host:
        - scikit-build-core
        - python
        - pip
        - nanobind
        # - nanobind-abi
        - ${{ pin_subpackage('fenics-libbasix', exact=True) }}
      run:
        - python
        - ${{ pin_subpackage('fenics-libbasix', exact=True) }}
        - numpy >=1.21
        - fenics-basix-nanobind-abi ==${{ abi_version }}
      run_exports:
        - fenics-basix-nanobind-abi ==${{ abi_version }}
    tests:
      - python:
          imports:
            - basix
          pip_check: true
      - files:
          source:
            - test
        requirements:
          run:
            - pip
            - pytest
            - pytest-xdist
            - if: not win
              then:
                - ${{ cxx_compiler }}
                - ${{ cxx_compiler }}_impl_${{ target_platform }}
              else:
                - vs_${{ target_platform }}
                - blas * openblas
            - ${{ compiler("cxx") }}
        script:
          - pytest -v test/test_create.py

  - package:
      name: fenics-basix-nanobind-abi
      version: ${{ abi_version }}
    requirements:
      run_exports:
        strong:
          - fenics-basix-nanobind-abi ==${{ abi_version }}
      run_constraints:
        - nanobind ${{ nanobind }}.*
        # - nanobind-abi ${{ nanobind_abi }}.*
        # confine to nanobind builds with nanobind_abi constraints
        - nanobind >=2.4
        - if: not win
          then:
            - ${{ cxx_compiler }} ${{ cxx_compiler_version }}.*
            - ${{ cxx_compiler }}_impl_${{ target_platform }} ${{ cxx_compiler_version }}.*
          else:
          - vs_${{ target_platform }} ${{ cxx_compiler_version }}.*
    tests:
      - script:
          - echo 'ok'

about:
  summary: Basix is a finite element definition and tabulation runtime library
  license: MIT
  license_file: LICENSE
  homepage: https://fenicsproject.org
  repository: https://github.com/fenics/basix
  documentation: https://docs.fenicsproject.org/basix/main/

extra:
  feedstock-name: fenics-basix
  recipe-maintainers:
    - minrk
